import type { NextPage } from 'next'
import type { Performer } from '@/lib/types'
import Head from 'next/head'
import { withAuth } from '@m3o/auth'
import { performers } from '@/lib/performers'
import { PerformerCard } from '@/components/PerformerCard'
import { MainLayout } from '@/components/MainLayout'
import { LandingBanner } from '@/components/LandingBanner'

interface Props {
  performers: Performer[]
}

export const getServerSideProps = withAuth<Props>({
  async onAuthentication() {
    const response = await performers.list()

    return {
      props: { performers: response },
    }
  },
})

const Home: NextPage<Props> = ({ performers }) => {
  return (
    <MainLayout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="bg-gray-50">
        <LandingBanner />
        <div className="p-6 md:grid md:grid-cols-4">
          <aside>1</aside>
          <div className="md:grid md:grid-cols-2 lg:grid-cols-3 2xl:grid-cols-4 col-span-3 gap-4">
            {performers.map((performer) => (
              <PerformerCard {...performer} key={performer.id} />
            ))}
          </div>
        </div>
      </div>
    </MainLayout>
  )
}

export default Home
