import type { Account } from 'm3o/user'
import type { NextPage } from 'next'
import type { Performer } from '@/lib/types'
import Head from 'next/head'
import { withAuth } from '@m3o/nextjs'
import { performers } from '@/lib/performers'
import { PerformersRow } from '@/components/PerformerRow'
import { MainLayout } from '@/components/MainLayout'
import { LandingBanner } from '@/components/LandingBanner'

interface HomeProps {
  performers: Performer[]
  user: Account
}

export const getServerSideProps = withAuth(async (context) => {
  const response = await performers.list()

  return {
    props: { user: context.req.user, performers: response } as HomeProps,
  }
})

const Home: NextPage<HomeProps> = ({ performers }) => {
  return (
    <MainLayout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LandingBanner />
      <div className="p-6">
        <PerformersRow performers={performers} title="test" />
      </div>
    </MainLayout>
  )
}

export default Home
